# Generated by Django 3.1.6 on 2021-02-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipeA',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipeB',
            field=models.CharField(max_length=16),
        ),
    ]
