# Generated by Django 3.1.6 on 2021-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210224_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='musique',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
