# Generated by Django 3.1.6 on 2021-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questions_musique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipeA',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipeB',
            field=models.CharField(max_length=27),
        ),
    ]
