# Generated by Django 3.1.6 on 2021-02-23 15:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('equipeA', models.CharField(max_length=50, unique=True)),
                ('equipeB', models.CharField(max_length=50, unique=True)),
                ('pointA', models.IntegerField(default=0)),
                ('pointB', models.IntegerField(default=0)),
                ('nbQuestion', models.IntegerField(default=1)),
            ],
        ),
    ]
